### PR TITLE
Lobby connection state UI layout

### PR DESCRIPTION
**Pull request by BigETI**
This pull request contains a lobby connection state user interface layout, which shows a player, if they are connecting, hide itself when connected, show up when player gets disconnected or kicked out of a lobby.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
No way to cancel. I somehow got stuck trying to connect to a lobby and nothing happened. Had to kill the app.

**Comment by BigETI** [comment]
Have you tested the latest build yet?

**Comment by Bios-Marcel** [comment]
good questiin, dunno. will do later

**Comment by Bios-Marcel** [comment]
The bug still happens. I created a lobby, left it and joined it again via "Find".

**Comment by BigETI** [comment]
I can't reproduce this issue. Are you sure you have the latest build installed?

**Comment by Bios-Marcel** [comment]
I clicked the commit and downloaded the artifact :shrug:

**Comment by BigETI** [comment]
That's not possible, because a timer of three seconds runs in the background to show a text that connection has failed, then two seconds later you will be thrown into the main menu. Please make sure you really have it installed.

**Comment by Bios-Marcel** [comment]
Could we get a commit hash somewhere in the app :D?

**Pull request merged**
