### PR TITLE
Lobby menus

### PR DESCRIPTION
**Pull request by BigETI**
This pull request contains lobby menus and various bug fixes.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
If you make PRs for me to check, it'd be good if I knew what I was looking for. I tested and menus seem to work fine. However, there's 300 changed files, I ahve no clue what actually changed. Instead of "fixed varius bugs", try to make smaller commits and explain what happened in each commit, This also gives as a cleaner history, allowing us to see what happened when and why.

Artifact worked fine btw. Not sure why it was a zip though, afaik apks are compressed either way. Might've been githubs fault.

**Comment by BigETI** [comment]
Sorry for the inconvenience but it's not easy to split changes into small commits, because those changes depend on each other. However most file changes come from the ScribblersSharp, where the commit history is located at https://github.com/scribble-rs/ScribblersSharp/commits/master

In this pull request you are really looking into lobby menus.

**Comment by BigETI** [comment]
The runner that is responsible for uploading artifacts create ZIP files no matter how many files are specified. https://github.com/actions/upload-artifact#zipped-artifact-downloads

Also GitHub artifacts are retained for 90 days maximum. https://github.com/actions/upload-artifact#retention-period

**Comment by Bios-Marcel** [comment]
Welp, in that case, feel free to merge. As far as I saw, lobby menus are just exit and resume anyways?

**Comment by BigETI** [comment]
It's more than that, but I will just merge it for now.

**Comment by Bios-Marcel** [comment]
> It's more than that, but I will just merge it for now.

Then what do I look at? If the commit message / PR message is too vague and the code changes too big, it's impossible for me to know what you mean.

**Comment by BigETI** [comment]
> Then what do I look at?

- Play menu
- Lobby creation/settings menu
- Lobby list

**Pull request merged**
