### PR TITLE
Art design

### PR DESCRIPTION
**Pull request by BigETI**
This pull request contains new art assets and animations for this game. The user interface including their behaviors have been changed to use the new art assets and animations, and much more!

I know the first commit in this pull request is large, but the changes depend on each other.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Let's go over this in a live session tomorrow. Overall I like it though.

**Comment by Bios-Marcel** [comment]
When live session

**Comment by Bios-Marcel** [comment]
Bugs:

* Pressing "Play" in the home menu and then pressing "back" (mobile) doesn't close the up, but reloads the home menu
* Pressing "Play" in the home menu and then pressing "back" and "Play" again and "back" again causes back to go forward sometimes. Instead it should always be "go one level higher".
* The audio mute/unmute button in the home menu does nothing and isn't grayed out.

UX/UI:

* New lobby view
  * The "Play" (create) buttons click array is the whole width of the parent, which is unexpected
  * The "Play" (create) button should probably not be centered, but left aligned .... on the other hand, i'd always expect right aligned and it annoys me that I have the X button everywhere on the right, maybe the X button should be on the left

* Lobby search view
  * If no lobby is available a placeholder would be nice (e.g. "There's no open lobbies").
  * There seems to be no loading indicator
  * There's no visual difference between the "internet" icon and the refresh icon, but you can click one of them

* Lobby view
  * The constant moving of the pencil is giving me a stroke
  * The `Round X/X` text is too small, paired with the animations, making it hard to read
  * I am not sure if it's fair to allow mobile users to chose pencil sizes inbetween the ones desktop offers (Might change this on desktop though)
  *  Menu
    * The "Exit game" message made me question whether it would close the app, how about "Leave lobby" instead
    * The play button reacts on taps of the whole width
    * The play button reacts to "moved, released" as a click, but it shouldn't, as this causes accidental menu closes
    * The X button in the menu is confusing, I thought i could close the menu that way, i really hate the x button, dunno man, in a mobile first experience, this button is not needed, because phones have a back button, whether virtual or physical (What about iPhone, I don't know)
    * The mute/unmute button also does nothing here as well
  * Color picker
    * Tapping on the triangle doesn't change the color, instead you have to drag the white "cursor", however, dragging outside of the cursor works

**Comment by BigETI** [comment]
Thank you for your feedback.

I'll merge it for now and concentrate on updating API, fixing bugs and adding stuff later.

**Pull request merged**
